from netcdf_api import NetCDF

# test
n1 = NetCDF("tos_O1_2001-2002.nc")
print ("the number of dimensions: ")
print (n1.ndims())
print ("the names of the dimensions: ")
print (n1.get_global_dim_names())
print ("the lengths of the dimensions: ")
print (n1.get_global_dim_lens())
print ("the number of variables: ")
print (n1.nvars())
print ("the names of variables stored in the data set: ")
print (n1.get_var_names())
print ("the dimensions of the input variable: ")
print (n1.get_var_dim_lens('tos'))
print ("the names of the dimensions for the variable: " )
print (n1.get_var_dim_names('tos'))
print ("the number of grid points that have the variable: ")
print (n1.get_num_of_points('tos'))
print ("the number of cells that have the variable: ")
print (n1.get_num_of_cells('tos'))
print ("the data array: ")
print (n1.get_data('tos'))
n1.plot_histogram('tos')